name: Comment when changes requested

on:
  workflow_run:
    workflows:
      - Trigger comment action
    types:
      - completed

jobs:
  call_workflow:
    name: Call workflow
    uses: ./.github/workflows/comment_when_changes_requested_core.yml