name: Comment when changes requested core

on: workflow_call

jobs:
  comment:
    name: Comment when changes requested
    if: ${{ github.event.review.state == 'changes_requested' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment
        run: gh pr comment ${{ github.event.pull_request.number }} --body '${{ github.event.review.user.login }} requested you to make some changes. Once changes are made, please re-request ${{ github.event.number }} to review by clicking "re-request review" button 🔄 (located in the reviewers list on the right side of this page).' --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ github.token }}