name: Comment when changes requested

on:
  pull_request_review:
    types:
      - submitted

jobs:
  call_workflow:
    name: Call workflow
    permissions:
      pull-requests: write
    uses: ./.github/workflows/comment_when_changes_requested_core.yml