name: Request review

on:
  pull_request_target:
    types:
      - opened
      - ready_for_review

jobs:
  call_workflow:
    name: Call workflow
    permissions:
      pull-requests: write
    uses: .github/workflows/request_review_core.yml@main
    with:
      reviewer: Gakuto1112