name: Trigger request review action

on:
  pull_request:
    types:
      - opened
      - ready_for_review

jobs:
  call_workflow:
    name: Call workflow
    uses: ./.github/workflows/request_review_trigger_core.yml